### ISSUE TITLE
Doesn't show USDC balance

### ISSUE THREAD

**Issue by natalietill** [Snowfork/snowbridge-app#36]
**Describe the bug**
Hi there. I connected my Talisman wallet, which has USDC on Asset Hub. When I choose USDC or any other currency, the account balance shows as 0. What is wrong? 

**To Reproduce**
1. Go to https://app.snowbridge.network/
2. Click on "from asset hub", "Connect wallet", 
3. Enter Talisman PW and allow connection from the wallet which is funded. Connection status in the Talisman extension is green. (4 accounts connected - I just connected them all). 
4. Select the funded account under "Account on the source." (I can see them all). 
5. Select currency underneath "amount". 
6. No matter which currency I choose, it says: "Balance: 0 USDC"

**Expected behavior**
The correct amount of USDC on the account I selected. 
**Screenshots**
<img width="725" alt="image" src="https://github.com/user-attachments/assets/b68da6b1-0120-47fe-8db0-d8c645ad2d05">

<img width="415" alt="image" src="https://github.com/user-attachments/assets/1789739f-b7f5-4803-b17c-b631a2d61570">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] Whatever is live

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alistair-singh** [comment]
Thanks for logging. Busy taking a look.

**Comment by alistair-singh** [comment]
Hi [natalietill](https://github.com/natalietill),

Asset Hub supports USDC in two forms. 
1. Native USDC.
2. USDC that is bridged from Ethereum.

The balance displayed in Snowbridge app is the bridged asset, that you have a zero balance for. The USDC that you see in your wallet is native USDC. These are not fungible and you will have to go through a pool to swap one for the other.

**Comment by natalietill** [comment]
Thank you @alistair-singh for your answer (even though it's not what I hoped for 😆 🙈 )!
