### ISSUE TITLE
NO response to load up the data

### ISSUE THREAD

**Issue by oakbay14** [Snowfork/snowbridge-app#39]
**Describe the bug**
Cannot load up the data and finish the bridging
**To Reproduce**
Senario A
1. Go to the main page 'https://app.snowbridge.network/'
2. waiting for a long day 
3. the balance and transfer fee is always fetching and connecting  for a whole day without any success

Senario B
1. Go to the main page 'https://app.snowbridge.network/'
2. Transfer the ETH token from Etherem network to Asset hub in Polkadot, the transaction is submitted and completed, the trancation hash is: 0x96f2498ad4d1fcb172db1edf7642ea155b80353aa4df4b0f8b1f879dc0629113
the event ID is:0x0a1e510c1b828f96fc1005fe858f7ff3697d7f766e0e81a20aff5ae9c475915d
My address is:0x3A46EE99fBd48cB132C815Ac6A7a5c22eD79c424
3.Error: there is no correspongding token transferred to the ASSET HUB address.

**Expected behavior**
I received my transferred token on Asset hub of Polkadot.

**Screenshots**
<img width="875" alt="image" src="https://github.com/user-attachments/assets/f0aa160e-8fac-4e91-8cab-6632a8399218">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : chrome
 - Version 130.0.6723.117

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alistair-singh** [comment]
> Scenario A

I cannot reproduce it. It may have been an intermittent network issue. If it persists, please provide more detail by looking at your console or network window. 

> Scenario B

You did not receive funds because the beneficiary address is a 20-byte EVM-style address, which Asset Hub does not support. The UI blocks this unless you explicitly allow it from your wallet. Please provide more information about the wallet you used and whether you have explicitly allowed EVM addresses?

E.g. with Talisman:
<img width="390" alt="image" src="https://github.com/user-attachments/assets/a0bd48fd-71cd-40a0-8b69-5fe1955ebcbc">

**Comment by oakbay14** [comment]
Thank you for help.
For scenario B, May I ask the question can I transferred ETH token from
ethereum network to bifrost network through the same Evm address?


Alistair Singh ***@***.***>于2024年11月11日 周一下午1:47写道：

**Comment by oakbay14** [comment]
The default wallet for beneficiary is maybe the SS58 address, I changed it
to EVM address, and then triggerd the crossing transaction.

Do you mean that I should transfer ETH to the SS58 address and then
transfer it to EMV address in bifrost through XCM?

oak stephen ***@***.***>于2024年11月11日 周一下午1:51写道：

**Comment by alistair-singh** [comment]
> For scenario B, May I ask the question can I transferred ETH token from ethereum network to bifrost network through the same Evm address?

I believe this is possible, but I am unsure how the EVM support works on Bifrost. So for now please use SS58 address to send to bifrost and then transfer to EVM address locally on Bifrost.

> Do you mean that I should transfer ETH to the SS58 address and then transfer it to EMV address in bifrost through XCM?

You do not have to do this in two steps. You can send to a SS58 address directly on Bifrost.  Bifrost is a fairly new addition and we are still adding support for all its features. I have reached out to the bifrost team to get more information about their EVM support and we will aim to add it soon.

**Comment by oakbay14** [comment]
Thank you so much for your help, later I will try your instructions

Alistair Singh ***@***.***>于2024年11月11日 周一下午3:02写道：
